version: '2'

services:
  master:
    image: chrislusf/seaweedfs:1.77
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
    volumes:
      - '/var/lib/weedfs/master:/data'
  volume:
    image: chrislusf/seaweedfs:1.77
    ports:
      - 9222:8080
      - 19222:18080
    command: 'volume -mserver="master:9333" -port=8080 -publicUrl=/file -ip=volume'
    volumes:
      - '/var/lib/weedfs/volume:/data'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:1.77
    ports:
      - 9255:8888
      - 19255:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    volumes:
      - '/var/lib/weedfs/filer:/data'
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs:1.77
    ports:
      - 9266:8333
    command: 's3 -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer
