version: '2'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
    command: "master"
    volumes:
      - '/var/lib/weedfs/master:/data'
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9222:8080
      - 19222:18080
    command: 'volume -max=1000 -mserver="master:9333" -port=8080 -publicUrl=/file'
    volumes:
      - '/var/lib/weedfs/volume:/data'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9255:8888
      - 19255:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    volumes:
      - '/var/lib/weedfs/filerdb:/data/filerdb'
    depends_on:
      - master
      - volume
  cronjob:
    image: chrislusf/seaweedfs # use a remote image
    command: 'cronjob'
    environment:
      # Run re-replication every 2 minutes
      CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
      WEED_MASTER: master:9333 # Default: localhost:9333
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9266:8333
    command: 's3 -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer