version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.6.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=Password_2020
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - gitea
    volumes:
      - /mnt/gitea/data:/data
    ports:
      - "10081:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8.0.13
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Password_2020
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=Password_2020
      - MYSQL_DATABASE=gitea
      - TZ=Asia/Shanghai
    networks:
      - gitea
    ports:
      - "3306:3306"
    volumes:
      - /mnt/gitea/mysql:/var/lib/mysql