#Default Kibana configuration for docker target
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://127.0.0.1:9200" ]
xpack.security.enabled: true
xpack.monitoring.ui.container.elasticsearch.enabled: true

# https://www.elastic.co/guide/en/kibana/current/reporting-settings-kb.html
xpack.reporting.encryptionKey: cfd336658112c55e97fe70f3bedb2040

# https://www.elastic.co/guide/en/kibana/7.1/using-kibana-with-security.html
xpack.security.encryptionKey: e10adc3949ba59abbe56e057f20f883e

# X-Pack security credentials
elasticsearch.username: elastic
elasticsearch.password: Password-2020