version: '2'
services:
  goaccess:
    build: .
    image: jayknoxqu/goaccess:v1.3
    restart: always
    container_name: goaccess
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    ports:
      - 7890:7890
    volumes:
      - /var/lib/goaccess:/goaccess
      - /var/lib/goaccess/goaccess.conf:/goaccess/goaccess.conf
      - /usr/local/nginx/logs/access.log:/goaccess/access.log
    command: [
                 "goaccess",
                 "--no-global-config",
                 "--config-file=/goaccess/goaccess.conf",
                 "--real-time-html",
                 "--output=/goaccess/index.html", 
                 "--with-output-resolver",
                 "--geoip-database=/var/www/goaccess/GeoLite2-City.mmdb",
                 "--ws-url=ws://example.com:80/goaccess",
                 "--log-file=/goaccess/access.log"
               ]