version: '2'
services:
  app:
    image: scottyhardy/docker-wine:latest
    restart: always
    working_dir: /work
    container_name: app
    environment:
      - LANG=zh_CN.UTF-8
      - RUN_AS_ROOT=yes
      - TZ=UTC-8
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /var/lib/work:/work
    command: wine app.exe -console
